backend:
  name: "git-gateway"
  accept_roles:
    - "admin"
    - "editor"
media_folder: "static/images"
collections:
  - name: "pages"
    label: "Pages"
    folder: "site/pages"
    identifier_field: "title"
    extension: "md"
    create: false
    delete: false
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Publish Date"
        name: "date"
        widget: "datetime"
      - label: "Layout"
        widget: "hidden"
        name: "layout"
        default: "{{slug}}.html"
      - label: "Seo"
        name: "seo"
        widget: "object"
        collapsed: true
        fields:
          - label: "Title"
            name: "title"
            widget: "string"
            required: false
          - label: "Description"
            name: "description"
            widget: "string"
            required: false
          - label: "Open Graph Image"
            name: "og:image"
            widget: "image"
            required: false
            media_library:
              config:
                multiple: false
          - label: "Twitter Card"
            name: "twitter:card"
            widget: "string"
            default: "summary"
            required: false
          - label: "Twitter Site"
            name: "twitter:site"
            widget: "string"
            required: false
          - label: "Twitter Creator"
            name: "twitter:creator"
            widget: "string"
            required: false
          - label: "Additional HTML tags"
            name: "additional_tags"
            widget: "text"
            required: false
  - name: "authors"
    label: "Authors"
    folder: "site/authors"
    create: true
    identifier_field: "name"
    extension: "md"
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - label: "Tags"
        widget: "hidden"
        name: "tags"
        default: "authors"
      - label: "Publish Date"
        name: "date"
        widget: "datetime"
      - label: "Layout"
        widget: "hidden"
        name: "layout"
        default: "single-authors.html"
      - label: "Seo"
        name: "seo"
        widget: "object"
        collapsed: true
        fields:
          - label: "Title"
            name: "title"
            widget: "string"
            required: false
          - label: "Description"
            name: "description"
            widget: "string"
            required: false
          - label: "Open Graph Image"
            name: "og:image"
            widget: "image"
            required: false
            media_library:
              config:
                multiple: false
          - label: "Twitter Card"
            name: "twitter:card"
            widget: "string"
            default: "summary"
            required: false
          - label: "Twitter Site"
            name: "twitter:site"
            widget: "string"
            required: false
          - label: "Twitter Creator"
            name: "twitter:creator"
            widget: "string"
            required: false
          - label: "Additional HTML tags"
            name: "additional_tags"
            widget: "text"
            required: false
      - label: "Body"
        name: "body"
        widget: "markdown"
        required: false
      - widget: "object"
        name: "picture"
        label: "Picture"
        fields:
          - widget: "image"
            name: "url"
            label: "Image"
            allow_multiple: false
            required: false
          - widget: "string"
            name: "alt"
            label: "Alt Text"
            required: false
      - name: "email"
        label: "Instagram Link (URL)"
        widget: "string"
        required: false
      - name: "twitter-profile-link"
        label: "Twitter Profile Link (URL)"
        widget: "string"
        required: false
      - name: "facebook-profile-link"
        label: "Facebook Profile Link (URL)"
        widget: "string"
        required: false
      - widget: "object"
        name: "banner-image"
        label: "Banner Image"
        fields:
          - widget: "image"
            name: "url"
            label: "Image"
            allow_multiple: false
            required: false
          - widget: "string"
            name: "alt"
            label: "Alt Text"
            required: false
      - name: "name"
        label: "Name"
        widget: "string"
        required: true
      - name: "created-on"
        label: "Created On"
        widget: "datetime"
        required: false
      - name: "updated-on"
        label: "Updated On"
        widget: "datetime"
        required: false
      - name: "published-on"
        label: "Published On"
        widget: "datetime"
        required: false
  - name: "categories"
    label: "Categories"
    folder: "site/categories"
    create: true
    identifier_field: "name"
    extension: "md"
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - label: "Tags"
        widget: "hidden"
        name: "tags"
        default: "categories"
      - label: "Publish Date"
        name: "date"
        widget: "datetime"
      - label: "Layout"
        widget: "hidden"
        name: "layout"
        default: "single-categories.html"
      - label: "Seo"
        name: "seo"
        widget: "object"
        collapsed: true
        fields:
          - label: "Title"
            name: "title"
            widget: "string"
            required: false
          - label: "Description"
            name: "description"
            widget: "string"
            required: false
          - label: "Open Graph Image"
            name: "og:image"
            widget: "image"
            required: false
            media_library:
              config:
                multiple: false
          - label: "Twitter Card"
            name: "twitter:card"
            widget: "string"
            default: "summary"
            required: false
          - label: "Twitter Site"
            name: "twitter:site"
            widget: "string"
            required: false
          - label: "Twitter Creator"
            name: "twitter:creator"
            widget: "string"
            required: false
          - label: "Additional HTML tags"
            name: "additional_tags"
            widget: "text"
            required: false
      - name: "color"
        label: "Color"
        widget: "color"
        required: false
      - widget: "object"
        name: "banner-image"
        label: "Banner Image"
        fields:
          - widget: "image"
            name: "url"
            label: "Image"
            allow_multiple: false
            required: false
          - widget: "string"
            name: "alt"
            label: "Alt Text"
            required: false
      - name: "name"
        label: "Name"
        widget: "string"
        required: true
      - name: "created-on"
        label: "Created On"
        widget: "datetime"
        required: false
      - name: "updated-on"
        label: "Updated On"
        widget: "datetime"
        required: false
      - name: "published-on"
        label: "Published On"
        widget: "datetime"
        required: false
  - name: "blog"
    label: "Blog Posts"
    folder: "site/blog"
    create: true
    identifier_field: "name"
    extension: "md"
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - label: "Tags"
        widget: "hidden"
        name: "tags"
        default: "blog"
      - label: "Publish Date"
        name: "date"
        widget: "datetime"
      - label: "Layout"
        widget: "hidden"
        name: "layout"
        default: "single-blog.html"
      - label: "Seo"
        name: "seo"
        widget: "object"
        collapsed: true
        fields:
          - label: "Title"
            name: "title"
            widget: "string"
            required: false
          - label: "Description"
            name: "description"
            widget: "string"
            required: false
          - label: "Open Graph Image"
            name: "og:image"
            widget: "image"
            required: false
            media_library:
              config:
                multiple: false
          - label: "Twitter Card"
            name: "twitter:card"
            widget: "string"
            default: "summary"
            required: false
          - label: "Twitter Site"
            name: "twitter:site"
            widget: "string"
            required: false
          - label: "Twitter Creator"
            name: "twitter:creator"
            widget: "string"
            required: false
          - label: "Additional HTML tags"
            name: "additional_tags"
            widget: "text"
            required: false
      - widget: "object"
        name: "hero-image"
        label: "Main Image"
        fields:
          - widget: "image"
            name: "url"
            label: "Image"
            allow_multiple: false
            required: true
          - widget: "string"
            name: "alt"
            label: "Alt Text"
            required: true
      - label: "Body"
        name: "body"
        widget: "markdown"
        required: false
      - name: "is-this-featured"
        label: "Is this featured?"
        widget: "boolean"
        required: false
      - widget: "relation"
        collection: "authors"
        value_field: "site/authors/{{slug}}.md"
        search_fields:
          - "slug"
          - "name"
        display_fields:
          - "name"
        required: false
        name: "authors"
      - name: "post-decription"
        label: "Post Decription"
        widget: "text"
        required: false
      - widget: "relation"
        collection: "categories"
        value_field: "site/categories/{{slug}}.md"
        search_fields:
          - "slug"
          - "name"
        display_fields:
          - "name"
        required: false
        name: "category"
      - name: "name"
        label: "Name"
        widget: "string"
        required: true
      - name: "created-on"
        label: "Created On"
        widget: "datetime"
        required: false
      - name: "updated-on"
        label: "Updated On"
        widget: "datetime"
        required: false
      - name: "published-on"
        label: "Published On"
        widget: "datetime"
        required: false
